compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  # deepspeed_multinode_launcher: standard
  # gradient_clipping: auto
  # offload_optimizer_device: cpu
  # offload_param_device: cpu
  zero3_init_flag: true
  # zero3_save_16bit_model: true
  # zero_stage: 3
  # zero_hpz_partition_size: 4
  deepspeed_config_file: /ceph/hpc/data/s24o01-42-users/translation_optimization/trl/deepspeed_config.json
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: ''
main_process_port: 29500
main_training_function: main
mixed_precision: bf16
num_machines: 2
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false